from ROOT import *

#Histograms 1D, FullSim Objects, general kinematics
hfjet_pt                 = TH1F("hfjet_pt","pT of all passing fat jets",40,200,1200)
hsfjet_pt                = TH1F("hsfjet_pt","pT of selected fat jet",40,200,1200)
hlfjet_pt                = TH1F("hlfjet_pt","pT of leading fat jet",40,200,1200)
hsfjet_btag              = TH1F("hsfjet_btag","btag value for selected fat jet",50,0,1.0)
#hfjet_unclus_pt          = TH1F("hfjet_unclus_pt","pT of all passing fat jets (unreclustered)",40,200,1200)
#hsfjet_unclus_pt         = TH1F("hsfjet_unclus_pt","pT of selected fat jet, unreclustered",40,200,1200)
hfjet_reclus_pt          = TH1F("hfjet_reclus_pt","pT of all passing fat jets (reclustered)",40,200,1200)
#hfj_unreclus_pt          = TH1F("hfj_unreclus_pt","unreclustered pT of fat jets that got reclustered",40,200,1200)
hfjet_mass               = TH1F("hfjet_mass","mass of all passing fat jets",80,0,400)
#hfjet_unlcus_mass        = TH1F("hfjet_unclus_mass","mass of all passing fat jets (unreclustered)",80,0,400)
hfjet_relcus_mass        = TH1F("hfjet_reclus_mass","mass of all passing fat jets (reclustered)",80,0,400)
#hfj_unrelcus_mass        = TH1F("hfj_unreclus_mass","unreclustered mass of fat jets that got reclustered",80,0,400)
hsfjet_mass              = TH1F("hsfjet_mass","mass of selected miniAOD fat jet",80,0,400)
#hsfjet_unclus_mass       = TH1F("hsfjet_unclus_mass","mass of selected miniAOD fat jet (unreclustered)",80,0,400)
hlfjet_mass              = TH1F("hlfjet_mass","mass of leading miniAOD fat jet",80,0,400)
hfjet_SD                 = TH1F("hfjet_SD","soft drop mass of all passing miniAOD fat jets",80,0,400)
#hfjet_unclus_SD          = TH1F("hfjet_unclus_SD","soft drop mass of all passing fat jets (unreclustered)",80,0,400)
hfjet_reclus_SD          = TH1F("hfjet_reclus_SD","soft drop mass of all passing fat jets (reclustered)",80,0,400)
#hfj_unreclus_SD          = TH1F("hfj_unreclus_SD","unreclustered soft drop of fat jets that got reclustered",80,0,400)
hsfjet_SD                = TH1F("hsfjet_SD","soft drop mass of selected miniAOD fat jet",80,0,400)
#hsfjet_unclus_SD         = TH1F("hsfjet_unclus_SD","soft drop mass of selected miniAOD fat jet (unreclustered)",80,0,400)
hlfjet_SD                = TH1F("hlfjet_SD","soft drop mass of leading miniAOD fat jet",80,0,400)
hmu_pt                   = TH1F("hmu_pt","pt of all acceptable muons",98,20,1000)
hmu1_pt                  = TH1F("hmu1_pt","pt of leading muon in pair closest to Z mass",98,20,1000)
hmu2_pt                  = TH1F("hmu2_pt","pt of subleading muon in pair closest to Z mass",98,20,1000)
hmutm_zcand_pt           = TH1F("hmutm_zcand_pt","pt of TreeMaker selected muons for Z cand",98,20,1000)
hmu_zcand_pt             = TH1F("hmu_zcand_pt","pt of script selected muons for Z cand",98,20,1000)
hzreco_pt                = TH1F("hzreco_pt","pt of reconstructed Z",80,0,800)
hztm_pt                  = TH1F("hztm_pt","pt of TreeMaker Z",80,0,800)
hzreco_mass              = TH1F("hzreco_mass","mass of reconstructed Z",20,70,110)
hztm_mass                = TH1F("hztm_mass","mass of TreeMaker Z",20,70,110)
hMETClean                = TH1F("hMETClean","cleaned misssing transverse momentum",78,50,2000)
hmt2200g                  = TH1F("hmt2200g","mt2 w/ guess of 200 GeV for NS",130,0,1300)
hmt2SD200g                = TH1F("hmt2SD200g","mt2 calculated with higgs SD w/ 200 GeV guess",130,0,1300)
hmt201g                  = TH1F("hmt201g","mt2 w/ guess of 1 GeV",130,0,1300)
hmt2SD01g                = TH1F("hmt2SD01g","mt2 calculated with higgs SD w/ guess of 1 GeV",130,0,1300)
hjigzp_mass              = TH1F("hjigzp_mass","mass estimator of Zp",100,500,5000)#25 GeV Bins
hjignd_mass              = TH1F("hjignd_mass","mass estimator of ND",130,0,1300)
hjigndbar_mass           = TH1F("hjigndbar_mass","mass estimator of NDbar",130,0,1300)
h2timemr1                = TH1F("h2timemr1","twice razor mass",100,500,5000)
hmr1                     = TH1F("hmr1","mR with 3 momenta",150,0,1800)
hmr2                     = TH1F("hmr2","mR with Energy",150,300,1800)
hmrt                     = TH1F("hmrt","mrt",130,0,1300)
hr1var                   = TH1F("hr1var","Razor mRT/mr1",20,0,2)
hr2var                   = TH1F("hr2var","Razor mRT/mr2",20,0,2)
hzh_mass                 = TH1F("hzh_mass","mass z+higgs",120,0,600)
hzh_pt                   = TH1F("hzh_pT","pT of leading z+h",40,200,1200)
hzMET_mt                 = TH1F("hzMET_mt","transerse mass Z and MET",130,0,1300)
hhMET_mt                 = TH1F("hhMET_mt","transerse mass h and MET",130,0,1300)
hht                      = TH1F("hht", "scalar sum of jet momentum",500,0,5000)
hst                      = TH1F("hsht", "scalar sum of jet and lepton momentum",500,0,5000)
hjignddiv                = TH1F("hjignddiv","jig nd/mnd",50,0,2)
hjigzpdiv                = TH1F("hjigzpdiv","jig zp/mzp",50,0,2)
h2razdiv                 = TH1F("h2razdiv","2*mr/mzp",50,0,2)
hzmtdiv                  = TH1F("hzmtdiv","mT (Z and MET) /mnd",50,0,2)
hmt2200div               = TH1F("hmt2200div","mt2 (200 GeV guess) /mnd",50,0,2)
hmt21div                 = TH1F("hmt21div","mt2 (1 GeV guess) /mnd",50,0,2)

#Overlap by region plots
#hdRgr8_unclus_pt         = TH1F("hdRgr8_unclus_pt","pT of unreclustered selec fat jet w/ dR > 0.8 btw closest muon",40,200,1200)
#hdRles8_both_unclus_pt   = TH1F("hdRles8_both_unclus_pt","pT of unreclustered selec fat jet w/ dR < 0.8 btw both muons",40,200,1200)
#hdRles8_one_unclus_pt    = TH1F("hdRles8_one_unclus_pt","pT of unreclustered selec fat jet w/ dR < 0.8 btw one muon",40,200,1200)
#hdRgr8_fjet_pt           = TH1F("hdRgr8_fjet_pt","pT of including reclus selec fat jet w/ original fat dR > 0.8 btw closest muon",40,200,1200)
#hdRles8_one_fjet_pt      = TH1F("hdRles8_one_fjet_pt","pT of including reclus selec fat jet w/ origninal dR < 0.8 btw one muon",40,200,1200)
#hdRles8_both_fjet_pt     = TH1F("hdRles8_both_fjet_pt","pT of including reclus selec fat jet w/ origninal dR < 0.8 btw both muons",40,200,1200)
#hdRgr8_unclus_SD         = TH1F("hdRgr8_unclus_SD","soft drop mass of unreclusted selc fat jet w/ dR > 0.8 btw closest muon",80,0,400)
#hdRles8_both_unclus_SD   = TH1F("hdRles8_both_unclus_SD","soft drop mass of unreclusted selec fat jet w/ dR < 0.8 btw both muons",80,0,400)
#hdRles8_one_unclus_SD    = TH1F("hdRles8_one_unclus_SD","soft drop mass of unreclusted selec fat jet w/ dR < 0.8 btw one muon",80,0,400)
#hdRgr8_fjet_SD           = TH1F("hdRgr8_fjet_SD","soft drop mass of including reclus selec fat jet w/ original dR > 0.8 btw closest muon",80,0,400)
#hdRles_both_fjet_SD      = TH1F("hdRles8_both_fjet_SD","soft drop mass of including reclus selec fat jet w/ original dR < 0.8 btw both muons",80,0,400)
#hdRles_one_fjet_SD       = TH1F("hdRles8_one_fjet_SD","soft drop mass of including reclus selec fat jet w/ original dR < 0.8 btw one muon",80,0,400)
#hdRgr8_unclus_mass       = TH1F("hdRgr8_unclus_mass","mass of unreclusted selec fat jet w/ dR > 0.8 btw closest muon",80,0,400)
#hdRles8_both_unclus_mass = TH1F("hdRles8_both_unclus_mass","mass of unreclusted selec fat jet w/ dR <= 0.8 btw both muons",80,0,400)
#hdRles8_one_unclus_mass  = TH1F("hdRles8_one_unclus_mass","mass of unreclusted selec fat jet w/ dR <= 0.8 btw one muon",80,0,400)
#hdRgr8_fjet_mass         = TH1F("hdRgr8_fjet_mass","mass of including reclus selec fat jet w/ original dR > 0.8 btw closest muon",80,0,400)
#hdRles8_both_fjet_mass   = TH1F("hdRles8_both_fjet_mass","mass of including reclus selec fat jet w/ original dR <= 0.8 btw both muons",80,0,400)
#hdRles8_one_fjet_mass    = TH1F("hdRles8_one_fjet_mass","mass of including reclus selec fat jet w/ original dR <= 0.8 btw one muon",80,0,400)

#Histograms 1D, Full Sim objects, Angles
hsfatdimuon_dR          = TH1F("hsfatdimuon_dR","delta R selected fat jet and seleceted Z",50,0,5)
hsfatdimuon_unclus_dR   = TH1F("hsfatdimuon_unclus_dR","delta R selected unreclustered fat jet and seleceted Z",50,0,5)
hsfatmu1_dR             = TH1F("hsfatmu1_dR","delta R selected fat jet and mu1",50,0,5)
hsfatmu2_dR             = TH1F("hsfatmu2_dR","delta R selected fat jet and mu2",50,0,5)
hmu1mu2_dR              = TH1F("hmu1mu2_dR","delta R mu1 and mu2",50,0,5)
hsfatdimuon_dphi        = TH1F("hsfatdimuon_dphi","delta phi selec fat and selec z",100,0,3.14159)
hsfatMET_dphi           = TH1F("hsfatMET_dphi","delta phi higgs and met",100,0,3.14159)
hdimuonMET_dphi         = TH1F("hdimuonMET_dphi","delta phi z and met",100,0,3.14159)
hsfat_phi               = TH1F("hsfat_phi","phi selec fat",100,0,3.14159)
hztm_phi                = TH1F("hztm_phi","phi zcandidate",100,0,3.14159)
hsfatdimuon_deta        = TH1F("hsfatdimuon_deta","delta eta selec fat and selec z",100,0,5)
hsfat_eta               = TH1F("hsfat_eta","eta selec fat",100,0,5)
hztm_eta                = TH1F("hztm_eta","eta zcandidate",100,0,5)
hMEtClean_phi           = TH1F("hMETClean_phi","pTmiss phi",100,0,3.14159)

#Histograms 1D, Gen Level
hghiggs_pt                  = TH1F("hghiggs_pt","pT of ghiggs",40,200,1200)
hghiggs_mass                = TH1F("hghiggs_mass","mass of gen higgs",60,0,600)
hnevents_dRg8_ghiggsgZ      = TH1F("hnevents_dRg8_ghiggsgZ","number of events with dR ghiggs and gZ > 0.8",1,0,1)
hnevents_dRles8_ghgZ_bothmu = TH1F("hnevents_dRles8_ghgZ_bothmu","number of events with both gen muons w/in 0.8 of higgs",1,0,1)
hnevents_dRles8_ghgZ_onemu  = TH1F("hnevents_dRles8_ghgZ_onemu","number of events with one gen muon w/in 0.8 of higgs",1,0,1)
hdRgr8_ghiggs_pt            = TH1F("hdRgr8_ghiggs_pt","pT of gen higgs jet w/ dR > 0.8 btw closest muon",40,200,1200)
hdRles8_both_ghiggs_pt      = TH1F("hdRles8_both_ghiggs_pt","pT of gen higgs jet w/ dR < 0.8 btw both muons",40,200,1200)
hdRles8_one_ghiggs_pt       = TH1F("hdRles8_one_ghiggs_pt","pT of gen higgs jet w/ dR < 0.8 btw one muon",40,200,1200)
hdRgr8_ghiggs_eta           = TH1F("hdRgr8_ghiggs_eta","eta of gen higgs jet w/ dR > 0.8 btw closest muon",100,-5,5)
hdRles8_both_ghiggs_eta     = TH1F("hdRles8_both_ghiggs_eta","eta of gen higgs jet w/ dR < 0.8 btw both muons",100,-5,5)
hdRles8_one_ghiggs_eta      = TH1F("hdRles8_one_ghiggs_eta","eta of gen higgs jet w/ dR < 0.8 btw one muon",100,-5,5)
hghiggsgZ_dphi              = TH1F("hghiggsgZ_dphi","delta phi gen higgs and gen z",100,0,3.14159)

#Histograms 1D, Phase Space Assessment
hbtagfrac                   = TH1F("hbtagfrac","fraction of fat jets/event w/ passing btag",100,0,1)
hnfatpass                   = TH1F("hnfatpass","number of passing fat jets/event",6,0,6)
hnevents                    = TH1F("hnevents","number of events",1,0,1)
hnevents_pZ                 = TH1F("hnevents_pZ","number of events with a passing Zcand",1,0,1)
hnevents_psf                = TH1F("hnevents_psf","number of events with a passing selected higgs cand",1,0,1)
hnevents_pMET               = TH1F("hnevents_pMET","number of events passing MET cut",1,0,1)
hdRgr8_unclus_fjmulti       = TH1F("hdRgr8_unclus_fjmulti","number of passing unclustered fats/event dR > 0.8",6,0,6)
hdRgr8_fjet_fjmulti         = TH1F("hdRgr8_fjet_fjmulti","number of passing fats/event dR > 0.8",6,0,6)
hdRles8_both_unclus_fjmulti = TH1F("hdRles8_both_unclus_fjmulti","number of passing unclus fats/event dR < 0.8 btwn both muons",6,0,6)
hdRles8_both_fjet_fjmulti   = TH1F("hdRles8_both_fjet_fjmulti","number of passing fats/event dR < 0.8 btwn both muons",6,0,6)
hdRles8_one_unclus_fjmulti  = TH1F("hdRles8_one_unclus_fjmulti","number of passing unclustered fats/event dR > 0.8 btwn one muon",6,0,6)
hdRles8_one_fjet_fjmulti    = TH1F("hdRles8_one_fjet_fjmulti","number of passing fats/event dR > 0.8 btwn one muon",6,0,6)

#Histograms 1D, comparision objects
hghlf_dphi = TH1F("hghlf_dphi","delta phi between gen higgs lead AK8",100,0,3.14159)
hghsf_dphi = TH1F("hghsf_dphi","delta phi between gen higgs selected AK8",100,0,3.14159)
    
#Histograms 2D
hghmvslfSD       = TH2F("hghmvslfSD","gen higgs mass vs. leading AK8 SD",12,0,600,60,90,150)
hghmvssfSD       = TH2F("hghmvssfSD","gen higgs mass vs. selected AK8 SD",12,0,600,60,90,150)
hghphivslfphi    = TH2F("hghphivslfphi","gen higgs phi vs. leading AK8 phi",100,0,3.14159,100,0,3.14159)
hghphivssfphi    = TH2F("hghphivssfphi","gen higgs phi vs. selected AK8 phi",100,0,3.14159,100,0,3.14159)
hlfphivssfphi    = TH2F("hlfphivssfphi","leading higgs phi vs. selected AK8 phi",100,0,3.14159,100,0,3.14159)
hghphivsnsfphi   = TH2F("hghphivsnsfphi","gen higgs phi vs. next selected AK8 phi",100,0,3.14159,100,0,3.14159)
hgZphivsdimuphi  = TH2F("hgZphivsdimuphi","gen Z phi vs. selected dimuon phi",100,0,3.14159,100,0,3.14159)

#Stack that ass up
hsgr8_pt            = THStack("hsgr8_pt","dR > 0.8 pT")
hsles8_both_pt      = THStack("hsles8_both_pt","dR < 0.8 for both Z muons pT")
hsles8_one_pt       = THStack("hsles8_one_pt","dR < 0.8 for one Z muon pT")
hsgr8_mass          = THStack("hsgr8_mass","dR > 0.8 invariant mass")
hsles8_both_mass    = THStack("hsles8_both_mass","dR < 0.8 for both Z muons inv mass")
hsles8_one_mass     = THStack("hsles8_one_mass","dR < 0.8 for one Z muon inv mass")
hsgr8_SD            = THStack("hsgr8_SD","dR > 0.8 soft drop mass")
hsles8_both_SD      = THStack("hsles8_both_SD","dR < 0.8 for both Z muons SD")
hsles8_one_SD       = THStack("hsles8_one_SD","dR < 0.8 for one Z muon SD")
hsgr8_fjmulti       = THStack("hsgr8_fjmulti","number of passing fat jets w/ dR > 0.8")
hsles8_both_fjmulti = THStack("hsles8_both_fjmulti","number of passing fat jets w/ dR < 0.8 for both Z muons")
hsles8_one_fjmulti  = THStack("hsles8_one_fjmulti","number of passing fat jets w/ dR < 0.8 for one Z muon")


